### PR TITLE
Update tests, `package.json`, and `README.md`

### PR DESCRIPTION
**Pull request by confused-Techie**
This PR updates some of the data in the repo, to rebrand to Pulsar, and follow our conventions.

Adding our own test running to the testing action on this, as well as updating the `README.md` and `package.json` with more modern info.

### CODE REVIEW

**Comment by sertonix** [comment]
Could you remove coffeelint too and add a `package-lock.json`?

**Comment by confused-Techie** [comment]
> Could you remove coffeelint too and add a `package-lock.json`?

I wasn't to sure about removing the coffee stuff, since there is CoffeeScript in the specs, but since we will very likely be removing it soon, you're right, I'll get rid of it.

**Comment by confused-Techie** [comment]
@Sertonix done

**Review by sertonix — APPROVED** [review]
As far as I can check this looks good. I will let the tests speak for themselfs.

**Comment by confused-Techie** [comment]
With tests passing, and an approval, I'll merge this one

**Pull request merged**
